# Generated by Django 4.1.7 on 2023-03-05 16:26

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogindexpage",
            name="content",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="blogindexpage",
            name="excerpt",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
