# Generated by Django 4.1.7 on 2023-03-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Blog author",
                "verbose_name_plural": "Blog authors",
            },
        ),
        migrations.AlterModelOptions(
            name="blogcategory",
            options={
                "verbose_name": "Blog category",
                "verbose_name_plural": "Blog categories",
            },
        ),
    ]
