# Generated by Django 4.1.7 on 2023-03-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_blogindexpage_content_blogindexpage_excerpt"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="date",
            field=models.DateField(null=True, verbose_name="Post date"),
        ),
    ]
