# Generated by Django 4.1.7 on 2023-03-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_blogauthor_alter_blogcategory_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogauthor",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
