# Generated by Django 4.1.7 on 2023-03-06 03:57

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_blogpage_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="Post date"
            ),
        ),
    ]
