# Generated by Django 4.1.7 on 2023-03-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_blogauthor_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogcategory",
            name="icon",
        ),
        migrations.AddField(
            model_name="blogcategory",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
