# Generated by Django 4.1.7 on 2023-03-06 04:08

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_blogpagegalleryimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogindexpage",
            name="intro",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
