# Generated by Django 4.1.7 on 2023-03-10 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_alter_blogcategory_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="blog.blogauthor",
            ),
        ),
    ]
