# Generated by Django 4.1.7 on 2023-03-06 04:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_blogindexpage_intro"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogindexpage",
            name="content",
        ),
        migrations.RemoveField(
            model_name="blogindexpage",
            name="excerpt",
        ),
    ]
