# Generated by Django 4.1.7 on 2023-03-16 17:33

import datetime

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("blog", "0006_blogpage_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogComment",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="Comment date"
                    ),
                ),
                ("content", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
