# Generated by Django 4.1.7 on 2023-02-26 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wordpress", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WPCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wp_id",
                    models.IntegerField(unique=True, verbose_name="Wordpress ID"),
                ),
                ("name", models.CharField(max_length=255)),
                ("count", models.IntegerField(default=0)),
                ("link", models.URLField()),
                ("slug", models.SlugField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wordpress.wpcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
    ]
