# Generated by Django 4.1.7 on 2023-03-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wordpress", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wpauthor",
            name="wp_cleaned_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wpcategory",
            name="wp_cleaned_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wpcomment",
            name="wp_cleaned_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wpmedia",
            name="wp_cleaned_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wppage",
            name="wp_cleaned_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wppost",
            name="wp_cleaned_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wptag",
            name="wp_cleaned_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
