# Generated by Django 4.1.7 on 2023-03-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wordpress", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wp_id",
                    models.IntegerField(unique=True, verbose_name="Wordpress ID"),
                ),
                ("wp_foreign_keys", models.JSONField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("count", models.IntegerField(default=0)),
                ("link", models.URLField()),
                ("slug", models.SlugField()),
                ("description", models.TextField(blank=True, null=True)),
                ("taxonomy", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
    ]
