# Generated by Django 4.1.7 on 2023-03-07 05:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wordpress", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wpcategory",
            options={
                "ordering": ["name"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
    ]
