# Generated by Django 4.1.7 on 2023-03-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wordpress", "0002_wptaxonomy_wpcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="wpcategory",
            name="wp_foreign_keys",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
