# Generated by Django 4.1.7 on 2023-03-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wordpress", "0002_wpauthor_wp_cleaned_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wpauthor",
            name="wp_block_content",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wpcategory",
            name="wp_block_content",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wpcomment",
            name="wp_block_content",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wpmedia",
            name="wp_block_content",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wppage",
            name="wp_block_content",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wppost",
            name="wp_block_content",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wptag",
            name="wp_block_content",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
