# Generated by Django 4.1.7 on 2023-03-04 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wordpress", "0002_wpmedia"),
    ]

    operations = [
        migrations.AddField(
            model_name="wpmedia",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wordpress.wpauthor",
            ),
        ),
    ]
