# Generated by Django 4.1.7 on 2023-03-03 21:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wordpress", "0002_tag"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tag",
            new_name="WPTag",
        ),
    ]
