# Generated by Django 4.1.7 on 2023-03-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wordpress", "0003_wpauthor_wp_block_content_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StreamBlockSignatureBlocks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("signature", models.CharField(max_length=255, unique=True)),
                ("block_name", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Stream Block Signature Blocks",
            },
        ),
    ]
