# Generated by Django 4.1.7 on 2023-03-03 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wordpress", "0004_wpauthor"),
    ]

    operations = [
        migrations.CreateModel(
            name="WPPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wp_id",
                    models.IntegerField(unique=True, verbose_name="Wordpress ID"),
                ),
                ("wp_foreign_keys", models.JSONField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("date", models.DateTimeField()),
                ("date_gmt", models.DateTimeField()),
                ("guid", models.URLField()),
                ("modified", models.DateTimeField()),
                ("modified_gmt", models.DateTimeField()),
                ("slug", models.SlugField()),
                ("status", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("link", models.URLField()),
                ("content", models.TextField(blank=True, null=True)),
                ("excerpt", models.TextField(blank=True, null=True)),
                ("comment_status", models.CharField(max_length=255)),
                ("ping_status", models.CharField(max_length=255)),
                ("sticky", models.BooleanField(default=False)),
                ("format", models.CharField(max_length=255)),
                ("template", models.CharField(max_length=255)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wordpress.wpauthor",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(blank=True, to="wordpress.wpcategory"),
                ),
                ("tags", models.ManyToManyField(blank=True, to="wordpress.wptag")),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
            },
        ),
    ]
