# Generated by Django 4.1.7 on 2023-03-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wordpress", "0004_streamblocksignatureblocks"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="streamblocksignatureblocks",
            options={
                "ordering": ["signature"],
                "verbose_name_plural": "Stream Block Signature Blocks",
            },
        ),
        migrations.AddField(
            model_name="streamblocksignatureblocks",
            name="block_kwargs",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
