# Generated by Django 4.1.7 on 2023-03-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wordpress", "0005_alter_streamblocksignatureblocks_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="streamblocksignatureblocks",
            name="model",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
