# Generated by Django 4.1.7 on 2023-03-30 22:50

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wordpress", "0007_wordpresshost"),
    ]

    operations = [
        migrations.CreateModel(
            name="WordpressEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("url", models.CharField(max_length=255, unique=True)),
                ("model", models.CharField(max_length=255, unique=True)),
                (
                    "setting",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wordpress_endpoints",
                        to="wordpress.wordpresshost",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
